default: &mysql
  adapter: mysql2
  username: 'deployer'
  password: 'mysqladmin'
  host: '128.199.93.241'

development:
  <<: *mysql
  database: capistrano_rails_dev

test:
  <<: *mysql
  database: capistrano_rails_test

production:
  <<: *mysql
  database: capistrano_rails
